config/routes.rb
Rails.application.routes.draw do
  
  
  #root 'bases#index'
  
  
  
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/edit_overwork_request'
      patch 'attendances/update_overwork_request'
    end
    
    collection do
      get 'atwork_members'
    end  
    
    collection { post :import }

    resources :attendances, only: :update

  end
  
  
  #root 'home#top'
 
  get 'bases/new', to: 'bases#new'
  post 'bases/create', to: 'bases#create'
  get 'bases/index', to: 'bases#index'
  get 'bases/:id', to: 'bases#show', as: :base
  get 'bases/:id/edit', to: 'bases#edit', as: :edit_base
  post 'bases/:id/update', to: 'bases#update', as: :update_base
  post 'bases/:id/destroy', to: 'bases#destroy', as: :destroy_base
  
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :attendances, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true    
  validates :department, length: {in: 2..50 },allow_blank: true    
  validates :basic_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 },allow_nil: true
  
  
  def User.digest(string)
    cost =
     if ActiveModel::SecurePassword.min_cost
       BCrypt::Engine::MIN_COST
     else 
       BCrypt::Engine.cost
     end 
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end  
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest,User.digest(remember_token))
  end  
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_passwprd?(remember_token)
  end  
  
  def forget
    update_attribute(:remember_digest,nil)
  end  
  
  def self.search(search)
   if search
     where(['content LILE ?', "%#{search}%"])
   else
     all
   end  
  end 
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      user = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      user.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    [ "name", "email","department","emploee_number","uid","password","basic_time","work_start_time","work_end_time"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit,:update]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info,:index,:update]
  before_action :admin_or_correct_user, only: :show
  before_action :set_one_month, only: :show

  def index
   @users = User.all 
  # if params[:name].present?
  #     @users = @users.get_by_name params[:name]
  # end
  #   if params[:id].present?
  #     @user = User.find_by(id: @users.id)
  #   else
  #     @user = User.new
  #   end

  end
  
  def import
    # fileはtmpに自動で一時保存される
     User.import(params[:file])
     flash[:success] = "ユーザー情報をインポートしました。"
     redirect_to users_url
  end   

  
  
  
  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :index     
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_basic_info
    
    
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + 
      @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  def atwork_members
   @user = User.all.includes(:attendances)
  
  end  

  private
    
    def user_params
      params.require(:user).permit(:department, :basic_time, :name, :email, :password, :emploee_number, :uid, :work_end_time, :work_start_time)
    end

    
    def basic_info_params
      params.require(:user).permit(:department, :basic_time, :name, :email, :password, :emploee_number, :uid, :work_end_time, :work_start_time)
    end  
    
    def admin_or_correct_user
      @user = User.find(params[:user_id]) if @user.blank?
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "編集権限がありません。"
        redirect_to(root_url)
      end  
    end

    # beforeフィルター

    # paramsハッシュからユーザーを取得します。
    
end

app/helpers/users_helper.rb
module UsersHelper

  # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
  <%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, "Confirmation", class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_form1.html.erb
  <%= form_with(model: user, url: update_basic_info_user_path(user), local: true, method: :patch) do |f| %>
 
  
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :emploee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :emploee_number, class: "form-control" %>
   
  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>
  
  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_time, class: "form-control" %>
  
  <%= f.label :work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :work_start_time, class: "form-control" %>
  
  <%= f.label :work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :work_end_time, class: "form-control" %>

  <%= f.submit "編集する", class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/atwork_members.erb
<h1>出勤社員一覧</h1>

<table class="table table-bordered ">
  <tr>
    <th>社員番号</th>
    <th>名前</th>
  </tr>
     
 <% @user.each do |user| %>
  <% user.attendances.each do |attendance| %>
   <% if (Date.current == attendance.worked_on) && attendance.started_at != nil && attendance.finished_at == nil %>
   <tr>
     <td><%= user.emploee_number %></td>
     <td><%= user.name %></td>
   </tr>
   <% end %>
  <% end %>
 <% end %>  
  
  
  
</table>



  

app/views/users/edit.html.erb
<% provide(:title,"Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>ユーザー一覧</h1>

<%= form_tag import_users_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%=  submit_tag "CSVをインポート", class: "btn btn-primary" %>
<% end %>

  
  <table class="table ">
   <% @users.each do |user| %>
    <tr>
      <td>
        <div class="col-md-22 col-md-offset-1">
        <% if current_user.admin? && !current_user?(user) %>
        <%= user.name %><br>
        | <%= link_to "削除", user, method: :delete,
                          data: { confirm: "削除してもよろしいですか？" },
                          class: "btn btn-primary btn-default" %><br>
          <div class="panel-group">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <button type="button" data-toggle="collapse" data-target="#collapse<%= user.id %>" class="btn btn-primary btn-lg">編集</button>
                </h4>
              </div>
              <div id="collapse<%= user.id %>" class="panel-collapse collapse">
                 <div class="panel-body"><%= render partial:'users/form1', locals:{ user: user } %></div>
                 
            </div>
          </div>
          <% end %>
        </div>
      </td>
    </tr>
  <% end %>
</table>
<!--モーダルウインドウ表示-->
<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'Signup') %>
<% provide(:button_text, '新規作成') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>
 

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>
        <%= link_to "⇦ ", user_path(date: @first_day.prev_month), class: "btn btn-info" %>
        【<%= l(@first_day, format: :middle) %>】勤怠管理表
        <%= link_to " ⇨", user_path(date: @first_day.next_month), class: "btn btn-info" %>
      </td>
      <td>指定勤務開始時間：<%= format_basic_info(@user.work_start_time) %><p>指定勤務終了時間：<%= format_basic_info(@user.work_end_time) %></p></td>
      <td colspan ="3">基本時間：<%= format_basic_info(@user.basic_time) %></td>
      <td>月初日：<%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>名前：<%= @user.name %></td>
      <td>社員番号</td>
      <td><%= @user.emploee_number %></td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>月末日：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<div class="btn-users-show">
  <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
  <%= link_to "CSV出力", "#",class: "btn btn-primary" %>
  <p><%= link_to "勤怠修正ログ（承認済）","#", class: "btn btn-primary" %></p>

<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="3">残業申請</th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th colspan="8">【実績】</th>
        <th colspan="5">【所定外勤務】</th>
      </tr>
    
      <tr>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        
      </tr>
    </thead>

    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td><%= link_to "残業申請",attendances_edit_overwork_request_user_path(@user,params:{ day: day.worked_on}),remote: true,class: "btn btn-primary" %></td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td>
            <% if day.worked_on.wday == 6 %>
             <font color ="Blue">土</font>
            <% elsif day.worked_on.wday == 0 %>
             <font color ="RED">日</font>
            <% else %>
             <%= $days_of_the_week[day.worked_on.wday] %>
            <% end %> 
          </td> 
          <td><%= day.started_at.strftime('%H') if day.started_at.present? %></td>
          <td><%= day.started_at.floor_to(15.minutes).strftime('%M') if day.started_at.present? %></td>
          <td>
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}登録", user_attendance_path(@user, day), 
              method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td><%= day.finished_at.strftime('%H') if day.finished_at.present? %></td>
          <td><%= day.finished_at.floor_to(15.minutes).strftime('%M') if day.finished_at.present? %></td>
          <td></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at, day.finished_at) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <!--<td>備考 </td> -->
          <!--<td>終了時間　時</td>-->
          <!--<td>終了時間分</td>-->
          <!--<td>時間外時間/td>-->
          <!--<td></td>-->
          <!--<td>指示者</td>-->
          
          
          </td>
        </tr>
      <% end %>
    </tbody>

    <tfoot>
      
      <tr>
        <td colspan="9"></td>
        <td colspan="1"><%= format("%.2f", @total_working_times.to_f) %></td>
        <td colspan="5"></td>
        
      </tr>
      
    </tfoot>    
  </table>
</div>

<div class="pull-right">
  <table class="table table-bordered table-condensed">
    <td>
      所属長承認　未<br>
      <%= link_to "申請","#",class: "btn btn-block btn-primary" %>
    </td>
  </table>
</div>


<!--モーダルウインドウ表示-->
<div id="edit-overwork-request" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>