config/routes.rb
Rails.application.routes.draw do
  
  
  #root 'bases#index'
  
  
  
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/edit_overwork_request'
      patch 'attendances/update_overwork_request'
    end
    
    collection do
      get 'atwork_members'
    end  
    
    collection { post :import }

    resources :attendances, only: :update

  end
  
  
  #root 'home#top'
 
  get 'bases/new', to: 'bases#new'
  post 'bases/create', to: 'bases#create'
  get 'bases/index', to: 'bases#index'
  get 'bases/:id', to: 'bases#show', as: :base
  get 'bases/:id/edit', to: 'bases#edit', as: :edit_base
  post 'bases/:id/update', to: 'bases#update', as: :update_base
  post 'bases/:id/destroy', to: 'bases#destroy', as: :destroy_base
  
end

app/controllers/bases_controller.rb
class BasesController < ApplicationController
  def index
    @bases = Base.all.order('id ASC')
    @base = Base.new
  end  
  
  def new
    @base = Base.new
  end  
  
  def create
    @base = Base.new(base_params)
    if @base.save
      flash[:success] = "拠点情報を作成しました。"
      redirect_to bases_index_url
    else
      flash[:notice] = "拠点情報の作成に失敗しました。"
      render :index
    end  
  end  
  
  def update
    if @base = Base.find(params[:id])
      @base.update(base_params)
      @base.save
      flash[:success] = "拠点情報を更新しました。"
      redirect_to bases_index_url
    else
      flash[:danger] = "更新に失敗しました。"
      redirect_to index
    end
  end  
  
  def destroy
    @base = Base.find(params[:id])
    @base.destroy
    flash[:success] = "#{@base.base_name}を削除しました"
    redirect_to bases_index_url
    
  end  
  
  private
   def base_params
     params.require(:base).permit(:base_number, :base_name, :base_type)
   end   
     
end

app/helpers/bases_helper.rb
module BasesHelper
end

app/views/bases/_edit_base.html.erb
<%= form_with(model: @base, url:update_base_path(base.id),local: true) do |f| %>
<%= render 'shared/error_messages_bases', object: @base %>

  <%=f.label :base_number, "拠点番号", class: "label--edit" %>
  <%= f.number_field :base_number, class: "form-control" %>
  
  <%=f.label :base_name, "拠点名", class: "label--edit" %>
  <%= f.text_field :base_name, class: "form-control" %>
  
  <%=f.label :base_type, "拠点種類", class: "label--edit" %>
  <%= f.select :base_type, {'出勤': '出勤', '退勤': '退勤'},class: "form-control form-control-lg", required: true %>
  
  <%= f.submit class: "btn btn-primary btn-block" %>
<% end %>

app/views/bases/_new_base.html.erb
<%= form_with(model: @base, url:bases_create_path,local: true) do |f| %>
<%= render 'shared/error_messages_bases', object: @base %>

  <%=f.label :base_number, "拠点番号", class: "label--edit" %>
  <%= f.number_field :base_number, class: "form-control" %>
  
  <%=f.label :base_name, "拠点名", class: "label--edit" %>
  <%= f.text_field :base_name, class: "form-control" %>
  
  <%=f.label :base_type, "拠点種類", class: "label--edit" %>
  <%= f.text_field :base_type, class: "form-control" %>
  
  <%= f.submit class: "btn btn-primary btn-block" %>
<% end %>  
  
  

app/views/bases/index.html.erb
<% provide(:tittle, "拠点一覧")%>
<h1>拠点一覧</h1>
<div>
  <table class="table table-bordered table-condensed table-hover">
    <thead>
      <tr>
        <th class="col-md-3"></th>
        <th class="col-md-2"></th>
        <th>拠点番号</th>
        <th>拠点名</th>
        <th>勤怠種類</th>
      </tr>  
    </thead>
   
    <tbody>
      <% @bases.each do |base| %>
      <tr>
        <td class="col-md-3">
          <div class="add_base">
            <div id="accordion<%= base.id %>">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion<%= base.id %>" href="#collapse<%= base.id %>">
                <button class="btn btn-primary btn-lg" type="button">修正</button></a>
              </h4>
            </div>
          </div>
        </td>
        <td>
          <%= link_to "削除",destroy_base_path(base.id), method: :post,
              data: { confirm: "#{base.base_name}を削除してよろしいですか？" },class: "btn btn-primary" %>
        </td>
        <td><%= base.base_number %></td>
        <td><%= base.base_name %></td>
        <td><%= base.base_type %></td>
      </tr>
      <tr>
        <td colspan="4">
          <div id="collapse<%= base.id %>" class="panel-collapse collapse">
            <div class="panel-body"><%= render 'bases/edit_base', {base: base} %></div>
          </div>
        </td>
      </tr>  
      <% end %>
    </tbody>
  </table>
</div>

<div class="add_base">
  <div class="panel-group" id="accordion">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapse">
            <button class="btn btn-primary btn-lg" type="button">拠点情報追加</button></a>
          </h4>
        </div>
      <div id="collapse" class="panel-collapse collapse">
        <div class="panel-body"><%= render 'bases/new_base' %></div>
      </div>
    </div>
  </div>
</div>

app/views/bases/new.html.erb
<h1>Bases#new</h1>
<p>Find me in app/views/bases/new.html.erb</p>